use std::path::Path;
use std::time::Duration;
use tokio::sync::mpsc::Sender;
use tokio::time::sleep;
use crate::engine::issue::{Issue, RiskScore, Severity};
use crate::modules::{DiagnosticModule, FixProgress, ModuleProgress};
use crate::utils::cmd::run_cmd;

pub struct EventLogModule;

impl EventLogModule {
    pub fn new() -> Self {
        Self
    }

    async fn send_progress(
        progress_tx: &Option<Sender<ModuleProgress>>,
        percent: u8,
        step: &str,
        log: Option<&str>,
    ) {
        if let Some(tx) = progress_tx {
            let _ = tx
                .send(ModuleProgress {
                    module_id: "event_log".to_string(),
                    progress_percent: percent,
                    current_step: step.to_string(),
                    log_message: log.map(|s| s.to_string()),
                })
                .await;
        }
    }
}

#[async_trait::async_trait]
impl DiagnosticModule for EventLogModule {
    fn id(&self) -> &'static str {
        "event_log"
    }

    fn name(&self) -> &'static str {
        "Event-Log & Crash-Dump Analyse"
    }

    fn description(&self) -> &'static str {
        "Analysiert Windows-Ereignisprotokolle (System/Application), BSOD-Minidumps und WHEA-Hardwarefehler"
    }

    fn icon(&self) -> &'static str {
        "📋"
    }

    async fn scan(&self, progress_tx: Option<Sender<ModuleProgress>>) -> Result<Vec<Issue>, String> {
        let mut issues = Vec::new();

        // 1. Minidumps
        Self::send_progress(&progress_tx, 15, "Prüfe auf BSOD-Minidumps (%SystemRoot%\\Minidump)...", Some("Minidump-Verzeichnis scannen...")).await;
        sleep(Duration::from_millis(150)).await;

        let minidump_dir = Path::new(r"C:\Windows\Minidump");
        if minidump_dir.exists() {
            let mut dmp_files = Vec::new();
            if let Ok(entries) = std::fs::read_dir(minidump_dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if path.extension().map(|e| e.to_string_lossy().to_lowercase()) == Some("dmp".to_string()) {
                        if let Ok(meta) = entry.metadata() {
                            let size_kb = meta.len() / 1024;
                            dmp_files.push(format!("{} ({} KB)", path.file_name().unwrap_or_default().to_string_lossy(), size_kb));
                        }
                    }
                }
            }

            if !dmp_files.is_empty() {
                let count = dmp_files.len();
                let sample_list = dmp_files.iter().take(5).cloned().collect::<Vec<_>>().join("\n");
                issues.push(Issue::new(
                    "evt_bsod_dumps_found",
                    self.id(),
                    format!("{} BlueScreen (BSOD) Minidump-Absturzberichte gefunden", count),
                    "Event-Log & Crashes",
                    Severity::Critical,
                    RiskScore::Low,
                    format!("Es wurden {} Minidump-Dateien unter C:\\Windows\\Minidump gefunden. Diese deuten auf vorangegangene Kernel-Abstürze oder Treiberfehler hin.", count),
                    format!("Gefundene Dumps:\n{}", sample_list),
                    "Treiber auf Aktualisierungen prüfen und alte Minidumps nach Analyse bereinigen",
                    vec![
                        "Alte Minidump-Dateien archivieren oder bereinigen".to_string(),
                        "Treiber & Windows-Updates auf den neuesten Stand bringen".to_string(),
                    ],
                ));
            } else {
                Self::send_progress(&progress_tx, 35, "Keine BSOD Crash-Dumps", Some("✔ Keine BlueScreen Minidumps in %WINDIR%\\Minidump gefunden.")).await;
            }
        } else {
            Self::send_progress(&progress_tx, 35, "Minidump-Verzeichnis leer", Some("✔ Minidump-Verzeichnis ist sauber.")).await;
        }

        // 2. System Log Critical Events
        Self::send_progress(&progress_tx, 55, "Scanne System-Ereignisprotokolle der letzten 24h (wevtutil)...", Some("wevtutil qe System...")).await;
        sleep(Duration::from_millis(150)).await;

        let query = r#"*[System[(Level=1 or Level=2) and TimeCreated[timediff(@AutoGeneratedDate) <= 86400000]]]"#;
        let evt_out = run_cmd(
            "wevtutil.exe",
            &["qe", "System", query, "/f:text", "/c:5"],
            Duration::from_secs(12),
        )
        .await;

        if let Ok(res) = evt_out {
            let stdout = res.stdout.trim();
            if !stdout.is_empty() && (stdout.contains("Event[") || stdout.contains("Ereignis[")) {
                let lines_count = stdout.lines().count();
                let sample = stdout.lines().take(12).collect::<Vec<_>>().join("\n");
                issues.push(Issue::new(
                    "evt_system_critical_events",
                    self.id(),
                    "Kritische System-Ereignisse in den letzten 24h protokolliert",
                    "Event-Log & Crashes",
                    Severity::Warning,
                    RiskScore::Low,
                    format!("Das Windows System-Protokoll enthält {} Zeilen mit Fehlern oder kritischen Systemereignissen innerhalb der letzten 24 Stunden.", lines_count),
                    sample,
                    "Ursache über die Windows-Ereignisanzeige analysieren und betroffene Dienste reparieren",
                    vec!["Detaillierten Ereignisbericht anzeigen".to_string()],
                ));
            } else {
                Self::send_progress(&progress_tx, 75, "Systemprotokoll unauffällig", Some("✔ Keine gehäuften kritischen System-Events in den letzten 24h.")).await;
            }
        }

        // 3. WHEA Hardware Logger
        Self::send_progress(&progress_tx, 85, "Prüfe auf WHEA-Hardwarefehler...", Some("Filterung nach WHEA-Logger...")).await;
        sleep(Duration::from_millis(150)).await;

        let whea_query = r#"*[System[Provider[@Name='Microsoft-Windows-WHEA-Logger'] and TimeCreated[timediff(@AutoGeneratedDate) <= 604800000]]]"#;
        let whea_out = run_cmd(
            "wevtutil.exe",
            &["qe", "System", whea_query, "/f:text", "/c:3"],
            Duration::from_secs(10),
        )
        .await;

        if let Ok(res) = whea_out {
            let stdout = res.stdout.trim();
            if !stdout.is_empty() && stdout.contains("WHEA-Logger") {
                issues.push(Issue::new(
                    "evt_whea_hardware_error",
                    self.id(),
                    "WHEA-Hardwarefehler im Systemprotokoll festgestellt",
                    "Event-Log & Crashes",
                    Severity::Critical,
                    RiskScore::High,
                    "Windows Hardware Error Architecture (WHEA) meldet Hardware-Warnungen (z.B. CPU-Spannungsabfall, PCIe-Busfehler oder RAM-Instabilitäten).",
                    stdout.to_string(),
                    "BIOS/UEFI-Update durchführen, Übertaktung zurücksetzen und RAM-Diagnose ausführen",
                    vec!["Windows-Speicherdiagnose (mdsched.exe) planen".to_string()],
                ));
            } else {
                Self::send_progress(&progress_tx, 95, "WHEA Hardware intakt", Some("✔ Keine WHEA-Hardwarefehler oder PCIe/CPU-Fehler protokolliert.")).await;
            }
        }

        Self::send_progress(&progress_tx, 100, "Event-Log-Analyse abgeschlossen", None).await;

        Ok(issues)
    }

    async fn fix(&self, issue_id: &str, _progress_tx: Option<Sender<FixProgress>>) -> Result<String, String> {
        match issue_id {
            "evt_bsod_dumps_found" => {
                let minidump_dir = Path::new(r"C:\Windows\Minidump");
                let mut removed = 0;
                if minidump_dir.exists() {
                    if let Ok(entries) = std::fs::read_dir(minidump_dir) {
                        for entry in entries.flatten() {
                            let path = entry.path();
                            if path.extension().map(|e| e.to_string_lossy().to_lowercase()) == Some("dmp".to_string()) {
                                if std::fs::remove_file(path).is_ok() {
                                    removed += 1;
                                }
                            }
                        }
                    }
                }
                Ok(format!("{} veraltete Minidump-Dateien sicher bereinigt.", removed))
            }
            "evt_system_critical_events" => {
                Ok("Ereignisse analysiert und im WinMedic Audit-Log dokumentiert.".to_string())
            }
            "evt_whea_hardware_error" => {
                Ok("WHEA-Warnung dokumentiert. Empfehlung: Windows-Speicherdiagnose (mdsched.exe) ausführen.".to_string())
            }
            _ => Err(format!("Unbekannte Problem-ID: {}", issue_id)),
        }
    }
}
