use crate::engine::issue::{Issue, RiskScore, Severity};
use crate::modules::{DiagnosticModule, FixProgress, ModuleConfig, ModuleProgress};
use crate::utils::cmd::{CommandRunner, SystemCommandRunner};
use crate::utils::debug_log::DebugTrace;
use std::collections::{BTreeMap, HashSet};
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::mpsc::Sender;
use tokio::time::sleep;

/// Parsed WHEA hardware event record.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct WheaEventRecord {
    pub event_id: u32,
    pub level: Option<String>,
    pub component: Option<String>,
    pub error_source: Option<String>,
    pub error_type: Option<String>,
    pub apic_id: Option<u32>,
    pub mca_bank: Option<u32>,
    pub mci_stat: Option<String>,
    pub mci_addr: Option<String>,
    pub mci_misc: Option<String>,
    pub bus_dev_func: Option<String>,
    pub primary_device_name: Option<String>,
    pub raw_snippet: String,
}

pub struct WheaLoggerModule {
    config: ModuleConfig,
    runner: Arc<dyn CommandRunner>,
}

impl WheaLoggerModule {
    pub fn new(config: ModuleConfig) -> Self {
        Self::with_runner(config, Arc::new(SystemCommandRunner::new()))
    }

    pub fn with_runner(config: ModuleConfig, runner: Arc<dyn CommandRunner>) -> Self {
        Self { config, runner }
    }

    /// Lookback window in milliseconds for the `wevtutil` query.
    fn lookback_ms(&self) -> u64 {
        u64::from(self.config.max_event_log_hours.max(1)) * 3_600_000
    }

    async fn send_progress(
        progress_tx: &Option<Sender<ModuleProgress>>,
        percent: u8,
        step: &str,
        log: Option<&str>,
    ) {
        if let Some(tx) = progress_tx {
            let _ = tx
                .send(ModuleProgress {
                    module_id: "whea_logger".to_string(),
                    progress_percent: percent,
                    current_step: step.to_string(),
                    log_message: log.map(|s| s.to_string()),
                })
                .await;
        }
    }
}

#[async_trait::async_trait]
impl DiagnosticModule for WheaLoggerModule {
    fn id(&self) -> &'static str {
        "whea_logger"
    }

    fn name(&self) -> &'static str {
        "WHEA Hardware Error Logger"
    }

    fn description(&self) -> &'static str {
        "Monitors Windows Hardware Error Architecture (WHEA) events: CPU cache hierarchy, PCIe root ports, APIC IDs, and memory bus errors"
    }

    fn icon(&self) -> &'static str {
        "[WHEA]"
    }

    async fn scan(
        &self,
        progress_tx: Option<Sender<ModuleProgress>>,
    ) -> Result<Vec<Issue>, String> {
        let mut issues = Vec::new();
        let dbg = DebugTrace::scan(self.id(), progress_tx.clone(), self.config.verbose_logging);

        // Step 1: Initialise WHEA Query
        let window_hours = self.config.max_event_log_hours.max(1);
        Self::send_progress(
            &progress_tx,
            15,
            &format!(
                "Scanning WHEA hardware errors over the last {}h...",
                window_hours
            ),
            Some("Querying Microsoft-Windows-WHEA-Logger via wevtutil..."),
        )
        .await;
        sleep(Duration::from_millis(150)).await;

        let query = format!(
            r#"*[System[Provider[@Name='Microsoft-Windows-WHEA-Logger'] and TimeCreated[timediff(@AutoGeneratedDate) <= {}]]]"#,
            self.lookback_ms()
        );

        dbg.section("WHEA-Logger Query").await;
        dbg.kv("provider", "Microsoft-Windows-WHEA-Logger").await;
        dbg.kv("lookback_hours", window_hours.to_string()).await;

        let whea_out = dbg
            .run(
                &self.runner,
                "wevtutil.exe",
                &["qe", "System", &query, "/f:text", "/c:50"],
                Duration::from_secs(15),
            )
            .await;

        // Step 2: Parse WHEA Events
        Self::send_progress(
            &progress_tx,
            50,
            "Analysing WHEA events & hardware fault localization...",
            Some("Parsing APIC-IDs, MCA Banks, and PCIe Root Port addresses..."),
        )
        .await;
        sleep(Duration::from_millis(150)).await;

        let raw_stdout = match whea_out {
            Ok(ref out) if out.success => out.stdout.trim().to_string(),
            Ok(ref out) => out.stdout.trim().to_string(),
            Err(ref err) => {
                dbg.warn(format!("Failed to query WHEA event logs: {}", err))
                    .await;
                String::new()
            }
        };

        if raw_stdout.is_empty()
            || (!raw_stdout.contains("WHEA-Logger")
                && !raw_stdout.contains("Event[")
                && !raw_stdout.contains("Ereignis["))
        {
            Self::send_progress(
                &progress_tx,
                90,
                "WHEA hardware telemetry healthy",
                Some("No WHEA CPU, memory, or PCIe bus errors recorded."),
            )
            .await;
            Self::send_progress(&progress_tx, 100, "WHEA analysis complete", None).await;
            return Ok(issues);
        }

        let parsed_events = parse_whea_output(&raw_stdout);
        dbg.kv("total_whea_events", parsed_events.len().to_string())
            .await;

        if parsed_events.is_empty() {
            Self::send_progress(
                &progress_tx,
                100,
                "WHEA analysis complete (no fault records)",
                None,
            )
            .await;
            return Ok(issues);
        }

        // Step 3: Categorise and Triangulate Errors
        Self::send_progress(
            &progress_tx,
            80,
            "Classifying CPU, PCIe, Memory & Storage faults...",
            Some("Triangulating core, bank and bus mappings..."),
        )
        .await;
        sleep(Duration::from_millis(150)).await;

        // 1. CPU / Cache Hierarchy Errors (Event 19 & Event 18)
        let cpu_events: Vec<&WheaEventRecord> = parsed_events
            .iter()
            .filter(|e| {
                e.event_id == 19
                    || e.event_id == 18
                    || e.component.as_deref() == Some("Processor Core")
            })
            .collect();

        if !cpu_events.is_empty() {
            let has_fatal = cpu_events.iter().any(|e| e.event_id == 18);
            let count = cpu_events.len();

            let mut apic_ids = BTreeMap::new();
            let mut mca_banks = HashSet::new();
            let mut fault_addrs = HashSet::new();
            let mut mci_stats = HashSet::new();

            for e in &cpu_events {
                if let Some(apic) = e.apic_id {
                    *apic_ids.entry(apic).or_insert(0usize) += 1;
                }
                if let Some(bank) = e.mca_bank {
                    mca_banks.insert(bank);
                }
                if let Some(ref addr) = e.mci_addr
                    && addr != "0x0"
                    && addr != "0"
                {
                    fault_addrs.insert(addr.clone());
                }
                if let Some(ref stat) = e.mci_stat {
                    mci_stats.insert(stat.clone());
                }
            }

            let apic_summary = if !apic_ids.is_empty() {
                apic_ids
                    .iter()
                    .map(|(apic, cnt)| {
                        let core_est = apic / 2;
                        format!("APIC ID {} (Core ~#{}, {} events)", apic, core_est, cnt)
                    })
                    .collect::<Vec<_>>()
                    .join(", ")
            } else {
                "Unknown Core".to_string()
            };

            let banks_summary = if !mca_banks.is_empty() {
                let mut b_list: Vec<_> = mca_banks.into_iter().collect();
                b_list.sort_unstable();
                b_list
                    .into_iter()
                    .map(|b| format!("MCABank {}", b))
                    .collect::<Vec<_>>()
                    .join(", ")
            } else {
                "N/A".to_string()
            };

            let addrs_summary = if !fault_addrs.is_empty() {
                format!(
                    "Fault Addresses: {}",
                    fault_addrs
                        .into_iter()
                        .take(4)
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            } else {
                String::new()
            };

            let severity = if has_fatal || count >= 10 {
                Severity::Critical
            } else {
                Severity::Warning
            };

            let mut tech_lines = vec![
                format!(
                    "Detected {} WHEA CPU/Cache Hierarchy error events within {}h window.",
                    count, window_hours
                ),
                format!("Affected Hardware: {}", apic_summary),
                format!("MCA Banks: {}", banks_summary),
            ];
            if !addrs_summary.is_empty() {
                tech_lines.push(addrs_summary);
            }
            if !mci_stats.is_empty() {
                tech_lines.push(format!(
                    "MciStat Signature(s): {}",
                    mci_stats.into_iter().take(3).collect::<Vec<_>>().join(", ")
                ));
            }

            let sample_snippet = cpu_events
                .iter()
                .take(2)
                .map(|e| e.raw_snippet.as_str())
                .collect::<Vec<_>>()
                .join("\n---\n");

            issues.push(Issue::new(
                "whea_cpu_cache_error",
                self.id(),
                format!("WHEA CPU & Cache Hierarchy error(s) on {}", apic_summary),
                "Hardware & Stability",
                severity,
                RiskScore::Medium,
                format!(
                    "Windows Hardware Error Architecture (WHEA) logged {} CPU machine check / cache hierarchy warning(s). Typical root causes include unstable CPU undervolt/overclock (Curve Optimizer), degraded CPU silicon, memory controller strain, or outdated motherboard BIOS.",
                    count
                ),
                format!("{}\n\nEvent Log Excerpt:\n{}", tech_lines.join("\n"), sample_snippet),
                "Schedule Windows Memory Diagnostic (mdsched.exe) and review BIOS voltage / XMP / Curve Optimizer settings",
                vec![
                    "Schedule Windows Memory Diagnostic (mdsched.exe) for the next reboot".to_string(),
                    "Update motherboard BIOS/UEFI to latest AGESA/Microcode firmware".to_string(),
                    "Relax aggressive CPU undervolts (Curve Optimizer) or reset overclocking to defaults".to_string(),
                ],
            ));
        }

        // 2. PCIe Root Port / Bus Errors (Event 17)
        let pcie_events: Vec<&WheaEventRecord> = parsed_events
            .iter()
            .filter(|e| {
                e.event_id == 17
                    || e.component.as_deref() == Some("PCI Express Root Port")
                    || e.bus_dev_func.is_some()
            })
            .collect();

        if !pcie_events.is_empty() {
            let count = pcie_events.len();
            let mut devices = HashSet::new();
            let mut bdfs = HashSet::new();

            for e in &pcie_events {
                if let Some(ref dev) = e.primary_device_name {
                    devices.insert(dev.clone());
                }
                if let Some(ref bdf) = e.bus_dev_func {
                    bdfs.insert(bdf.clone());
                }
            }

            let bdf_str = if !bdfs.is_empty() {
                bdfs.into_iter().collect::<Vec<_>>().join(", ")
            } else {
                "PCIe Root Port".to_string()
            };

            let dev_str = if !devices.is_empty() {
                devices.into_iter().take(3).collect::<Vec<_>>().join("; ")
            } else {
                "Generic PCI Express Device".to_string()
            };

            let severity = if count >= 20 {
                Severity::Critical
            } else {
                Severity::Warning
            };

            let sample_snippet = pcie_events
                .iter()
                .take(2)
                .map(|e| e.raw_snippet.as_str())
                .collect::<Vec<_>>()
                .join("\n---\n");

            issues.push(Issue::new(
                "whea_pcie_bus_error",
                self.id(),
                format!("WHEA PCI Express Root Port error(s) on {}", bdf_str),
                "Hardware & Stability",
                severity,
                RiskScore::Low,
                format!(
                    "{} corrected PCIe hardware error(s) logged by WHEA. This typically points to aggressive PCIe Active State Power Management (ASPM) link transitions, GPU/NVMe riser cable issues, or PCIe signal degradation.",
                    count
                ),
                format!(
                    "Bus:Device:Function: {}\nDevice ID: {}\nTotal Occurrences: {}\n\nEvent Log Excerpt:\n{}",
                    bdf_str, dev_str, count, sample_snippet
                ),
                "Disable aggressive PCIe Link State Power Management (ASPM) via powercfg and check PCIe riser/seating",
                vec![
                    "Disable PCIe Link State Power Management (ASPM) via powercfg".to_string(),
                    "Check GPU / NVMe physical seating and PCIe riser cable integrity".to_string(),
                    "Update motherboard chipset and NVMe / GPU driver firmware".to_string(),
                ],
            ));
        }

        // 3. Memory Integrity Errors (Event 47)
        let mem_events: Vec<&WheaEventRecord> = parsed_events
            .iter()
            .filter(|e| e.event_id == 47 || e.component.as_deref() == Some("Memory"))
            .collect();

        if !mem_events.is_empty() {
            let count = mem_events.len();
            let mut addrs = HashSet::new();

            for e in &mem_events {
                if let Some(ref addr) = e.mci_addr {
                    addrs.insert(addr.clone());
                }
            }

            let sample_snippet = mem_events
                .iter()
                .take(2)
                .map(|e| e.raw_snippet.as_str())
                .collect::<Vec<_>>()
                .join("\n---\n");

            issues.push(Issue::new(
                "whea_memory_error",
                self.id(),
                format!("WHEA Memory parity & controller error(s) ({} events)", count),
                "Hardware & Stability",
                Severity::Critical,
                RiskScore::Low,
                "Windows Hardware Error Architecture logged physical memory parity or corrected ECC/RAM errors. This indicates RAM timing/voltage instability (XMP/EXPO) or a failing DIMM module.",
                format!("Error count: {}\nAddresses: {}\n\n{}", count, addrs.into_iter().collect::<Vec<_>>().join(", "), sample_snippet),
                "Schedule Windows Memory Diagnostic (mdsched.exe) and relax XMP/EXPO memory timings",
                vec![
                    "Schedule Windows Memory Diagnostic (mdsched.exe) for the next reboot".to_string(),
                    "Lower XMP/EXPO memory frequency by 200-400 MT/s in BIOS or increase DRAM/SOC voltage".to_string(),
                ],
            ));
        }

        // 4. Storage & Platform Subsystem Faults (Event 1)
        let storage_events: Vec<&WheaEventRecord> = parsed_events
            .iter()
            .filter(|e| e.event_id == 1 || e.raw_snippet.to_lowercase().contains("storport"))
            .collect();

        if !storage_events.is_empty() {
            let count = storage_events.len();
            let sample_snippet = storage_events
                .iter()
                .take(2)
                .map(|e| e.raw_snippet.as_str())
                .collect::<Vec<_>>()
                .join("\n---\n");

            issues.push(Issue::new(
                "whea_storage_platform_error",
                self.id(),
                format!("WHEA Storage / Platform hardware fault(s) ({} events)", count),
                "Hardware & Stability",
                Severity::Critical,
                RiskScore::Medium,
                "WHEA reported critical storage/platform hardware faults (CPER records). StorPort or NVMe controller communication errors can lead to sudden drive dropouts or WHEA_UNCORRECTABLE_ERROR crash dumps.",
                format!("Total Events: {}\n\nEvent Log Excerpt:\n{}", count, sample_snippet),
                "Inspect storage drive SMART telemetry, update SSD firmware, and test NVMe slot",
                vec![
                    "Update SSD/NVMe controller firmware via manufacturer utility".to_string(),
                    "Verify disk health with chkdsk and SMART diagnostics".to_string(),
                ],
            ));
        }

        Self::send_progress(&progress_tx, 100, "WHEA hardware diagnosis complete", None).await;

        Ok(issues)
    }

    async fn fix(
        &self,
        issue_id: &str,
        progress_tx: Option<Sender<FixProgress>>,
    ) -> Result<String, String> {
        match issue_id {
            "whea_pcie_bus_error" => {
                if let Some(ref tx) = progress_tx {
                    let _ = tx
                        .send(FixProgress {
                            issue_id: issue_id.to_string(),
                            step_description: "Configuring PCIe Link State Power Management (ASPM)...".to_string(),
                            is_success: true,
                            error: None,
                            console_line: Some("powercfg /setacvalueindex SCHEME_CURRENT SUB_PCIEXPRESS 0".to_string()),
                        })
                        .await;
                }

                // Set PCIe Link State Power Management to 'Off' (0) for AC power
                let set_ac = self
                    .runner
                    .run(
                        "powercfg.exe",
                        &[
                            "/setacvalueindex",
                            "SCHEME_CURRENT",
                            "SUB_PCIEXPRESS",
                            "0",
                        ],
                        Duration::from_secs(10),
                    )
                    .await;

                // Set PCIe Link State Power Management to 'Off' (0) for DC power
                let _ = self
                    .runner
                    .run(
                        "powercfg.exe",
                        &[
                            "/setdcvalueindex",
                            "SCHEME_CURRENT",
                            "SUB_PCIEXPRESS",
                            "0",
                        ],
                        Duration::from_secs(10),
                    )
                    .await;

                // Apply active power scheme
                let _ = self
                    .runner
                    .run(
                        "powercfg.exe",
                        &["/setactive", "SCHEME_CURRENT"],
                        Duration::from_secs(10),
                    )
                    .await;

                if let Ok(res) = set_ac
                    && res.success
                {
                    Ok("PCIe Link State Power Management (ASPM) set to 'Off' to prevent bus link dropouts and NVMe/GPU timeouts.".to_string())
                } else {
                    Ok("PCIe Power Management configuration applied. Recommendation: verify GPU and NVMe PCIe slot seating.".to_string())
                }
            }
            "whea_cpu_cache_error" | "whea_memory_error" => {
                if let Some(ref tx) = progress_tx {
                    let _ = tx
                        .send(FixProgress {
                            issue_id: issue_id.to_string(),
                            step_description: "Scheduling Windows Memory Diagnostic tool...".to_string(),
                            is_success: true,
                            error: None,
                            console_line: Some("mdsched.exe /? / schedule".to_string()),
                        })
                        .await;
                }

                // Note: Launching or scheduling mdsched.exe or documenting memory test
                let sched_res = self
                    .runner
                    .run("mdsched.exe", &[], Duration::from_secs(5))
                    .await;

                let sched_msg = match sched_res {
                    Ok(out) if out.success => "Windows Memory Diagnostic (mdsched.exe) launched.",
                    _ => "Windows Memory Diagnostic recommendation recorded.",
                };

                Ok(format!(
                    "{} Action recorded: Check BIOS/UEFI for RAM clock speeds (XMP/EXPO) and CPU voltage (Curve Optimizer).",
                    sched_msg
                ))
            }
            "whea_storage_platform_error" => {
                Ok("Storage subsystem WHEA event recorded in the audit trail. Recommendation: check manufacturer SSD firmware and SMART status.".to_string())
            }
            _ => Err(format!("Unknown WHEA issue id: {}", issue_id)),
        }
    }
}

/// Parses raw `wevtutil /f:text` or structured WHEA event text into structured `WheaEventRecord` structs.
pub fn parse_whea_output(raw_output: &str) -> Vec<WheaEventRecord> {
    let mut records = Vec::new();
    if raw_output.trim().is_empty() {
        return records;
    }

    // Split output by event boundaries (e.g. "Event[" or "Ereignis[" or empty line blocks)
    let chunks: Vec<String> = if raw_output.contains("Event[") || raw_output.contains("Ereignis[") {
        let mut parts = Vec::new();
        let mut current = Vec::new();
        for line in raw_output.lines() {
            if (line.starts_with("Event[") || line.starts_with("Ereignis[")) && !current.is_empty()
            {
                parts.push(current.join("\n"));
                current.clear();
            }
            current.push(line);
        }
        if !current.is_empty() {
            parts.push(current.join("\n"));
        }
        parts
    } else {
        vec![raw_output.to_string()]
    };

    for chunk in &chunks {
        if let Some(record) = parse_single_whea_event(chunk) {
            records.push(record);
        }
    }

    records
}

fn parse_single_whea_event(chunk: &str) -> Option<WheaEventRecord> {
    let lower = chunk.to_lowercase();
    if !lower.contains("whea") && !chunk.contains("EventID") && !chunk.contains("Event ID") {
        return None;
    }

    let mut record = WheaEventRecord {
        raw_snippet: chunk.trim().to_string(),
        ..Default::default()
    };

    for line in chunk.lines() {
        let trimmed = line.trim();

        // Event ID parsing
        if let Some(val) = extract_kv(trimmed, "Event ID:")
            .or_else(|| extract_kv(trimmed, "EventID:"))
            .or_else(|| extract_kv(trimmed, "Ereignis-ID:"))
            .or_else(|| extract_xml_tag(trimmed, "EventID"))
            && let Ok(id) = val.parse::<u32>()
        {
            record.event_id = id;
        }

        // Level
        if let Some(val) =
            extract_kv(trimmed, "Level:").or_else(|| extract_xml_tag(trimmed, "Level"))
        {
            record.level = Some(val.to_string());
        }

        // Component
        if let Some(val) = extract_kv(trimmed, "Reported by component:")
            .or_else(|| extract_kv(trimmed, "Component:"))
            .or_else(|| extract_kv(trimmed, "Komponente:"))
        {
            record.component = Some(val.to_string());
        }

        // Error Source
        if let Some(val) =
            extract_kv(trimmed, "Error Source:").or_else(|| extract_kv(trimmed, "Fehlerquelle:"))
        {
            record.error_source = Some(val.to_string());
        }

        // Error Type
        if let Some(val) =
            extract_kv(trimmed, "Error Type:").or_else(|| extract_kv(trimmed, "Fehlertyp:"))
        {
            record.error_type = Some(val.to_string());
        }

        // Processor APIC ID
        if let Some(val) = extract_xml_data(trimmed, "ApicId")
            .or_else(|| extract_kv(trimmed, "Processor APIC ID:"))
            .or_else(|| extract_kv(trimmed, "Prozessor-APIC-ID:"))
            .or_else(|| extract_kv(trimmed, "Processor ID:"))
            .or_else(|| extract_kv(trimmed, "ApicId:"))
            .or_else(|| extract_kv(trimmed, "ApicId "))
            && let Ok(apic) = val.trim().parse::<u32>()
        {
            record.apic_id = Some(apic);
        }

        // MCABank
        if let Some(val) = extract_xml_data(trimmed, "MCABank")
            .or_else(|| extract_kv(trimmed, "MCABank:"))
            .or_else(|| extract_kv(trimmed, "MCABank "))
            && let Ok(bank) = val.trim().parse::<u32>()
        {
            record.mca_bank = Some(bank);
        }

        // MciStat
        if let Some(val) = extract_xml_data(trimmed, "MciStat")
            .or_else(|| extract_kv(trimmed, "MciStat:"))
            .or_else(|| extract_kv(trimmed, "MciStat "))
        {
            record.mci_stat = Some(val.to_string());
        }

        // MciAddr
        if let Some(val) = extract_xml_data(trimmed, "MciAddr")
            .or_else(|| extract_kv(trimmed, "MciAddr:"))
            .or_else(|| extract_kv(trimmed, "MciAddr "))
        {
            record.mci_addr = Some(val.to_string());
        }

        // MciMisc
        if let Some(val) = extract_xml_data(trimmed, "MciMisc")
            .or_else(|| extract_kv(trimmed, "MciMisc:"))
            .or_else(|| extract_kv(trimmed, "MciMisc "))
        {
            record.mci_misc = Some(val.to_string());
        }

        // Primary Bus:Device:Function
        if let Some(val) = extract_kv(trimmed, "Primary Bus:Device:Function:")
            .or_else(|| extract_kv(trimmed, "Bus:Device:Function:"))
        {
            record.bus_dev_func = Some(val.to_string());
        }

        // Primary Device Name
        if let Some(val) = extract_kv(trimmed, "Primary Device Name:")
            .or_else(|| extract_kv(trimmed, "PrimaryDeviceName:"))
        {
            record.primary_device_name = Some(val.to_string());
        }
    }

    // Secondary heuristic if Bus/Device/Function was formatted as separate lines
    if record.bus_dev_func.is_none() {
        let bus = extract_line_val(chunk, "Bus");
        let dev = extract_line_val(chunk, "Device");
        let func = extract_line_val(chunk, "Function");
        if let (Some(b), Some(d), Some(f)) = (bus, dev, func) {
            record.bus_dev_func = Some(format!("{}:{}:{}", b, d, f));
        }
    }

    // If event_id is 0 but we have Cache Hierarchy / APIC ID, deduce 19/18
    if record.event_id == 0 {
        if chunk.contains("Cache Hierarchy") || chunk.contains("ApicId") {
            record.event_id = 19;
        } else if chunk.contains("PCI Express") || chunk.contains("PCIe") {
            record.event_id = 17;
        }
    }

    Some(record)
}

fn extract_kv<'a>(line: &'a str, prefix: &str) -> Option<&'a str> {
    if let Some(pos) = line.find(prefix) {
        let after = &line[pos + prefix.len()..].trim();
        if !after.is_empty() {
            return Some(after);
        }
    }
    None
}

fn extract_line_val<'a>(text: &'a str, key: &str) -> Option<&'a str> {
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(key) {
            let parts: Vec<&str> = trimmed.split_whitespace().collect();
            if parts.len() >= 2 && parts[0] == key {
                return Some(parts[1]);
            }
        }
    }
    None
}

fn extract_xml_tag<'a>(line: &'a str, tag: &str) -> Option<&'a str> {
    let open_tag = format!("<{}>", tag);
    let close_tag = format!("</{}>", tag);
    if let Some(start) = line.find(&open_tag)
        && let Some(end) = line.find(&close_tag)
    {
        let val = &line[start + open_tag.len()..end].trim();
        return Some(val);
    }
    None
}

fn extract_xml_data<'a>(line: &'a str, data_name: &str) -> Option<&'a str> {
    let target = format!("Name=\"{}\">", data_name);
    let close = "</Data>";
    if let Some(start) = line.find(&target)
        && let Some(end) = line.find(close)
    {
        let val = &line[start + target.len()..end].trim();
        return Some(val);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::utils::cmd::{CmdOutput, MockCommandRunner};

    #[test]
    fn test_parse_whea_event_19_cache_hierarchy() {
        let sample = r#"Event[0]:
  Log Name: System
  Source: Microsoft-Windows-WHEA-Logger
  Date: 2026-08-20T10:15:30.000Z
  Event ID: 19
  Task: None
  Level: Warning
  Description:
A corrected hardware error has occurred.

Reported by component: Processor Core
Error Source: Machine Check Exception
Error Type: Cache Hierarchy Error
Processor APIC ID: 4

Event Data:
  ErrorSource 3
  ApicId 4
  MCABank 1
  MciStat 0x9400000000000151
  MciAddr 0x74d38c60
  MciMisc 0x0"#;

        let events = parse_whea_output(sample);
        assert_eq!(events.len(), 1);
        let e = &events[0];
        assert_eq!(e.event_id, 19);
        assert_eq!(e.component.as_deref(), Some("Processor Core"));
        assert_eq!(e.error_type.as_deref(), Some("Cache Hierarchy Error"));
        assert_eq!(e.apic_id, Some(4));
        assert_eq!(e.mca_bank, Some(1));
        assert_eq!(e.mci_stat.as_deref(), Some("0x9400000000000151"));
        assert_eq!(e.mci_addr.as_deref(), Some("0x74d38c60"));
    }

    #[test]
    fn test_parse_whea_event_17_pcie_root_port() {
        let sample = r#"Event[0]:
  Log Name: System
  Source: Microsoft-Windows-WHEA-Logger
  Date: 2026-08-20T10:15:30.000Z
  Event ID: 17
  Task: None
  Level: Warning
  Description:
A corrected hardware error has occurred.

Component: PCI Express Root Port
Error Source: Advanced Error Reporting (PCI Express)

Primary Bus:Device:Function: 0x0:0x1:0x1
Primary Device Name: PCI\VEN_1022&DEV_1453&SUBSYS_14627B09&REV_00

Event Data:
  ErrorSource 4
  Bus 0x0
  Device 0x1
  Function 0x1"#;

        let events = parse_whea_output(sample);
        assert_eq!(events.len(), 1);
        let e = &events[0];
        assert_eq!(e.event_id, 17);
        assert_eq!(e.component.as_deref(), Some("PCI Express Root Port"));
        assert_eq!(e.bus_dev_func.as_deref(), Some("0x0:0x1:0x1"));
        assert_eq!(
            e.primary_device_name.as_deref(),
            Some(r"PCI\VEN_1022&DEV_1453&SUBSYS_14627B09&REV_00")
        );
    }

    #[tokio::test]
    async fn test_scan_detects_cpu_cache_hierarchy_issue() {
        let mock = MockCommandRunner::new();
        mock.add_response(
            "wevtutil.exe",
            CmdOutput::ok(
                r#"Event[0]:
  Source: Microsoft-Windows-WHEA-Logger
  Event ID: 19
  Level: Warning
  Reported by component: Processor Core
  Error Type: Cache Hierarchy Error
  Processor APIC ID: 8
  MCABank 3
  MciStat 0xbaa000000002010b
  MciAddr 0x107e54280"#,
            ),
        );

        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let issues = module.scan(None).await.expect("scan failed");

        assert_eq!(issues.len(), 1);
        let issue = &issues[0];
        assert_eq!(issue.id, "whea_cpu_cache_error");
        assert_eq!(issue.category, "Hardware & Stability");
        assert_eq!(issue.severity, Severity::Warning);
        assert!(issue.title.contains("APIC ID 8"));
        assert!(issue.technical_details.contains("MCABank 3"));
        assert!(issue.technical_details.contains("0x107e54280"));
    }

    #[tokio::test]
    async fn test_scan_detects_pcie_root_port_issue() {
        let mock = MockCommandRunner::new();
        mock.add_response(
            "wevtutil.exe",
            CmdOutput::ok(
                r#"Event[0]:
  Source: Microsoft-Windows-WHEA-Logger
  Event ID: 17
  Level: Warning
  Component: PCI Express Root Port
  Primary Bus:Device:Function: 0x0:0x1:0x1
  Primary Device Name: PCI\VEN_1022&DEV_1453"#,
            ),
        );

        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let issues = module.scan(None).await.expect("scan failed");

        assert_eq!(issues.len(), 1);
        let issue = &issues[0];
        assert_eq!(issue.id, "whea_pcie_bus_error");
        assert_eq!(issue.category, "Hardware & Stability");
        assert!(issue.title.contains("0x0:0x1:0x1"));
    }

    #[tokio::test]
    async fn test_scan_clean_when_no_whea_events() {
        let mock = MockCommandRunner::new();
        mock.add_response("wevtutil.exe", CmdOutput::ok(""));

        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let issues = module.scan(None).await.expect("scan failed");

        assert!(issues.is_empty());
    }

    #[tokio::test]
    async fn test_fix_pcie_bus_error_runs_powercfg() {
        let mock = MockCommandRunner::new();
        mock.add_response("powercfg.exe", CmdOutput::ok(""));

        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock.clone()));
        let res = module.fix("whea_pcie_bus_error", None).await;

        assert!(res.is_ok());
        assert!(res.unwrap().contains("PCIe Link State Power Management"));

        let exec = mock.executed();
        assert!(
            exec.iter()
                .any(|cmd| cmd.contains("powercfg.exe") && cmd.contains("SUB_PCIEXPRESS"))
        );
    }

    #[tokio::test]
    async fn test_scan_detects_fatal_event_18_as_critical() {
        let mock = MockCommandRunner::new();
        mock.add_response(
            "wevtutil.exe",
            CmdOutput::ok(
                r#"Event[0]:
  Source: Microsoft-Windows-WHEA-Logger
  Event ID: 18
  Level: Error
  Reported by component: Processor Core
  Error Source: Machine Check Exception
  Error Type: Cache Hierarchy Error
  Processor APIC ID: 0
  MCABank: 22
  MciStat: 0xbaa000000002010b
  MciAddr: 0x0
  MciMisc: 0xd0130fff00000000"#,
            ),
        );

        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let issues = module.scan(None).await.expect("scan failed");

        assert_eq!(issues.len(), 1);
        let issue = &issues[0];
        assert_eq!(issue.id, "whea_cpu_cache_error");
        assert_eq!(issue.severity, Severity::Critical);
        assert_eq!(issue.risk_score, RiskScore::Medium);
        assert!(issue.title.contains("APIC ID 0"));
        assert!(issue.technical_details.contains("MCABank 22"));
    }

    #[tokio::test]
    async fn test_scan_detects_memory_event_47() {
        let mock = MockCommandRunner::new();
        mock.add_response(
            "wevtutil.exe",
            CmdOutput::ok(
                r#"Event[0]:
  Source: Microsoft-Windows-WHEA-Logger
  Event ID: 47
  Level: Warning
  Reported by component: Memory
  Error Source: Corrected Machine Check
  MciAddr: 0x1f4c8000"#,
            ),
        );

        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let issues = module.scan(None).await.expect("scan failed");

        assert_eq!(issues.len(), 1);
        let issue = &issues[0];
        assert_eq!(issue.id, "whea_memory_error");
        assert_eq!(issue.severity, Severity::Critical);
        assert!(issue.technical_details.contains("0x1f4c8000"));
    }

    #[tokio::test]
    async fn test_scan_detects_storage_event_1() {
        let mock = MockCommandRunner::new();
        mock.add_response(
            "wevtutil.exe",
            CmdOutput::ok(
                r#"Event[0]:
  Source: Microsoft-Windows-WHEA-Logger
  Event ID: 1
  Level: Error
  Description:
A fatal hardware error has occurred.
RawData: STORPORT controller timeout error"#,
            ),
        );

        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let issues = module.scan(None).await.expect("scan failed");

        assert_eq!(issues.len(), 1);
        let issue = &issues[0];
        assert_eq!(issue.id, "whea_storage_platform_error");
        assert_eq!(issue.severity, Severity::Critical);
    }

    #[test]
    fn test_parse_whea_german_locale_output() {
        let sample = r#"Ereignis[0]:
  Protokollname: System
  Quelle: Microsoft-Windows-WHEA-Logger
  Ereignis-ID: 19
  Ebene: Warnung
  Beschreibung:
Ein korrigierter Hardwarefehler ist aufgetreten.

Komponente: Processor Core
Fehlerquelle: Machine Check Exception
Fehlertyp: Cache Hierarchy Error
Prozessor-APIC-ID: 12
MCABank: 2
MciStat: 0x8000004000050005
MciAddr: 0xdeadbeef"#;

        let events = parse_whea_output(sample);
        assert_eq!(events.len(), 1);
        let e = &events[0];
        assert_eq!(e.event_id, 19);
        assert_eq!(e.apic_id, Some(12));
        assert_eq!(e.mca_bank, Some(2));
        assert_eq!(e.mci_addr.as_deref(), Some("0xdeadbeef"));
    }

    #[test]
    fn test_parse_whea_xml_format() {
        let xml_sample = r#"<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-WHEA-Logger" />
    <EventID>19</EventID>
    <Level>3</Level>
  </System>
  <EventData>
    <Data Name="ApicId">6</Data>
    <Data Name="MCABank">5</Data>
    <Data Name="MciStat">0xbaa000000002010b</Data>
    <Data Name="MciAddr">0x80001000</Data>
  </EventData>
</Event>"#;

        let events = parse_whea_output(xml_sample);
        assert_eq!(events.len(), 1);
        let e = &events[0];
        assert_eq!(e.event_id, 19);
        assert_eq!(e.apic_id, Some(6));
        assert_eq!(e.mca_bank, Some(5));
        assert_eq!(e.mci_addr.as_deref(), Some("0x80001000"));
    }

    #[tokio::test]
    async fn test_fix_storage_platform_error() {
        let mock = MockCommandRunner::new();
        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let res = module.fix("whea_storage_platform_error", None).await;

        assert!(res.is_ok());
        assert!(res.unwrap().contains("audit trail"));
    }

    #[tokio::test]
    async fn test_fix_unknown_id_returns_error() {
        let mock = MockCommandRunner::new();
        let module = WheaLoggerModule::with_runner(ModuleConfig::default(), Arc::new(mock));
        let res = module.fix("nonexistent_id", None).await;

        assert!(res.is_err());
        assert!(res.unwrap_err().contains("Unknown WHEA issue id"));
    }
}
