//! Windows event records as `wevtutil qe ... /f:xml` prints them.
//!
//! The text rendering (`/f:text`) is localized: its field labels, the level
//! names and the event message all come out in the display language, so a
//! parser written against it works on the languages its author tried and on no
//! other. The XML rendering is the event itself — provider, event id, level,
//! timestamp and the named `EventData` fields — and reads the same on every
//! Windows.
//!
//! The XML is machine-written and flat, so a scanner over the handful of
//! elements WinMedic reads is enough; there is no general XML parser here.

use crate::utils::cmd::CmdOutput;

/// The `wevtutil` arguments for the newest `max_events` System-log events that
/// match `filter` and were logged within the last `lookback_ms`, as XML.
///
/// `filter` is the inside of `System[...]`, e.g. `(Level=1 or Level=2)`.
///
/// Two things here are easy to get wrong, and every query WinMedic made got
/// both wrong on every Windows, in every language:
///
/// - the XPath goes in `/q:`. Passed as a bare argument, `wevtutil` rejects the
///   whole command ("too many arguments", exit code 87);
/// - the age filter is `timediff(@SystemTime)`. `@AutoGeneratedDate` names no
///   attribute, so a filter on it matched no event ever logged.
///
/// Either one alone left the event checks blind, and neither showed, because a
/// refused query was read as an empty log. [`read_events`] no longer does that.
pub fn system_log_query(filter: &str, lookback_ms: u64, max_events: usize) -> Vec<String> {
    vec![
        "qe".to_string(),
        "System".to_string(),
        format!("/q:*[System[{filter} and TimeCreated[timediff(@SystemTime) <= {lookback_ms}]]]"),
        "/f:xml".to_string(),
        format!("/c:{max_events}"),
        // Newest first, so a capped result is the most recent events.
        "/rd:true".to_string(),
    ]
}

/// The events in a `wevtutil qe` result, or why there are none to read.
///
/// No matching event is exit code 0 and no output; a non-zero exit code means
/// the query itself was refused, which is an error and not an empty log.
pub fn read_events(output: Result<CmdOutput, String>) -> Result<Vec<EventRecord>, String> {
    let out = output.map_err(|e| format!("wevtutil could not be run: {e}"))?;
    if !out.success {
        let message = if out.stderr.trim().is_empty() {
            out.stdout.trim()
        } else {
            out.stderr.trim()
        };
        return Err(format!(
            "wevtutil refused the event log query (exit code {}): {}",
            out.exit_code
                .map(|code| code.to_string())
                .unwrap_or_else(|| "none".to_string()),
            message.lines().next().unwrap_or("")
        ));
    }
    Ok(parse_events(&out.stdout))
}

/// One event, with the parts of it the modules decide on.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct EventRecord {
    pub provider: String,
    pub event_id: u32,
    /// 1 critical, 2 error, 3 warning, 4 information.
    pub level: Option<u8>,
    /// `SystemTime`, UTC, as Windows wrote it: `2026-08-19T18:51:42.9518113Z`.
    pub time_created: Option<String>,
    /// The `EventData` fields in order; unnamed `<Data>` elements have an
    /// empty name.
    pub data: Vec<(String, String)>,
}

impl EventRecord {
    /// The value of the `EventData` field called `name`.
    pub fn data(&self, name: &str) -> Option<&str> {
        self.data
            .iter()
            .find(|(field, _)| field == name)
            .map(|(_, value)| value.as_str())
    }

    /// `2026-08-19 18:51:42 UTC  Microsoft-Windows-Kernel-Power  Event 41`
    pub fn summary(&self) -> String {
        let when = self
            .time_created
            .as_deref()
            .map(|t| format!("{} UTC", t.get(..19).unwrap_or(t).replace('T', " ")))
            .unwrap_or_else(|| "unknown time".to_string());
        format!("{}  {}  Event {}", when, self.provider, self.event_id)
    }

    /// The summary line followed by one line per data field, for a finding's
    /// technical details. Blobs such as `RawData` are left out: kilobytes of
    /// hex explain nothing to the reader.
    pub fn details(&self) -> String {
        let mut out = self.summary();
        for (name, value) in &self.data {
            if name.is_empty() || name == "RawData" || value.len() > 200 {
                continue;
            }
            out.push_str(&format!("\n  {}: {}", name, value));
        }
        out
    }
}

/// Every `<Event>` in `xml`, in the order `wevtutil` printed them.
pub fn parse_events(xml: &str) -> Vec<EventRecord> {
    let mut events = Vec::new();
    let mut rest = xml;
    while let Some(start) = find_element(rest, "Event") {
        let body = &rest[start..];
        let end = body
            .find("</Event>")
            .map(|at| at + "</Event>".len())
            .unwrap_or(body.len());
        events.push(parse_event(&body[..end]));
        rest = &body[end..];
    }
    events
}

fn parse_event(event: &str) -> EventRecord {
    let provider = start_tag(event, "Provider")
        .and_then(|tag| attribute(tag, "Name"))
        .unwrap_or_default();
    let event_id = element_text(event, "EventID")
        .and_then(|id| id.trim().parse().ok())
        .unwrap_or(0);
    let level = element_text(event, "Level").and_then(|level| level.trim().parse().ok());
    let time_created = start_tag(event, "TimeCreated").and_then(|tag| attribute(tag, "SystemTime"));

    let mut data = Vec::new();
    if let Some(section) = element_text(event, "EventData") {
        let mut rest = section;
        while let Some(at) = find_element(rest, "Data") {
            let element = &rest[at..];
            let Some(tag_end) = element.find('>') else {
                break;
            };
            let tag = &element[..tag_end];
            let name = attribute(tag, "Name").unwrap_or_default();
            if tag.ends_with('/') {
                data.push((name, String::new()));
                rest = &element[tag_end + 1..];
                continue;
            }
            let content = &element[tag_end + 1..];
            let value_end = content.find("</Data>").unwrap_or(content.len());
            data.push((name, unescape(&content[..value_end])));
            rest = &content[value_end..];
        }
    }

    EventRecord {
        provider,
        event_id,
        level,
        time_created,
        data,
    }
}

/// Where the element `name` starts — `<name` followed by a space, `>` or `/`,
/// so `<Data` does not match `<DataItem`.
fn find_element(text: &str, name: &str) -> Option<usize> {
    let open = format!("<{name}");
    let mut from = 0;
    while let Some(at) = text[from..].find(&open) {
        let start = from + at;
        match text[start + open.len()..].chars().next() {
            Some(' ' | '>' | '/' | '\t' | '\r' | '\n') => return Some(start),
            _ => from = start + open.len(),
        }
    }
    None
}

/// The start tag of the first `name` element, without its closing `>`.
fn start_tag<'a>(text: &'a str, name: &str) -> Option<&'a str> {
    let start = find_element(text, name)?;
    let tag = &text[start..];
    Some(&tag[..tag.find('>')?])
}

/// The raw text between the first `<name ...>` and its `</name>`.
fn element_text<'a>(text: &'a str, name: &str) -> Option<&'a str> {
    let element = &text[find_element(text, name)?..];
    let tag_end = element.find('>')?;
    if element[..tag_end].ends_with('/') {
        return Some("");
    }
    let content = &element[tag_end + 1..];
    let end = content.find(&format!("</{name}>"))?;
    Some(&content[..end])
}

/// An attribute value, in either quote style.
fn attribute(tag: &str, name: &str) -> Option<String> {
    for quote in ['\'', '"'] {
        let key = format!(" {name}={quote}");
        if let Some(at) = tag.find(&key) {
            let value = &tag[at + key.len()..];
            let end = value.find(quote)?;
            return Some(unescape(&value[..end]));
        }
    }
    None
}

fn unescape(text: &str) -> String {
    if !text.contains('&') {
        return text.to_string();
    }
    text.replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

#[cfg(test)]
mod tests {
    use super::*;

    // Real events from a German Windows 11 (computer name replaced). Nothing in
    // them is localized, which is the reason for reading XML.
    const KERNEL_POWER_41: &str = include_str!("../../tests/fixtures/events/kernel_power_41.xml");
    const WER_BUGCHECK: &str = include_str!("../../tests/fixtures/events/wer_bugcheck_1001.xml");
    const SYSTEM_ERRORS: &str = include_str!("../../tests/fixtures/events/system_errors.xml");

    #[test]
    fn reads_provider_id_level_time_and_data() {
        let events = parse_events(KERNEL_POWER_41);
        assert_eq!(events.len(), 2);
        let first = &events[0];
        assert_eq!(first.provider, "Microsoft-Windows-Kernel-Power");
        assert_eq!(first.event_id, 41);
        assert_eq!(first.level, Some(1));
        assert_eq!(
            first.time_created.as_deref(),
            Some("2026-08-19T18:51:42.9518113Z")
        );
        assert_eq!(first.data("BugcheckCode"), Some("0"));
        assert_eq!(first.data("LongPowerButtonPressDetected"), Some("false"));
        assert_eq!(first.data("NoSuchField"), None);
    }

    #[test]
    fn reads_the_stop_code_of_a_bugcheck_event() {
        let events = parse_events(WER_BUGCHECK);
        assert_eq!(events.len(), 1);
        assert_eq!(
            events[0].provider,
            "Microsoft-Windows-WER-SystemErrorReporting"
        );
        assert_eq!(events[0].event_id, 1001);
        assert!(
            events[0]
                .data("param1")
                .unwrap()
                .starts_with("0x0000009f (")
        );
    }

    #[test]
    fn an_event_id_with_qualifiers_still_parses() {
        let events = parse_events(SYSTEM_ERRORS);
        assert_eq!(events.len(), 5);
        assert_eq!(events[0].provider, "Service Control Manager");
        assert_eq!(events[0].event_id, 7023);
        assert_eq!(events[0].level, Some(2));
        assert_eq!(events[0].data("param1"), Some("HvHost"));
    }

    #[test]
    fn summary_and_details_are_readable() {
        let event = &parse_events(KERNEL_POWER_41)[0];
        assert_eq!(
            event.summary(),
            "2026-08-19 18:51:42 UTC  Microsoft-Windows-Kernel-Power  Event 41"
        );
        assert!(event.details().contains("\n  BugcheckCode: 0"));
    }

    #[test]
    fn empty_and_self_closing_data_and_entities() {
        let xml = "<Event xmlns='x'><System><Provider Name='A &amp; B'/><EventID>7</EventID></System>\
                   <EventData><Data Name='Empty'/><Data Name='Text'>a &lt;b&gt;</Data><Data>anon</Data></EventData></Event>";
        let events = parse_events(xml);
        assert_eq!(events.len(), 1);
        assert_eq!(events[0].provider, "A & B");
        assert_eq!(events[0].level, None);
        assert_eq!(events[0].data("Empty"), Some(""));
        assert_eq!(events[0].data("Text"), Some("a <b>"));
        assert_eq!(events[0].data(""), Some("anon"));
    }

    #[test]
    fn the_query_is_passed_the_way_wevtutil_accepts_it() {
        let args = system_log_query("(Level=1 or Level=2)", 86_400_000, 5);
        assert_eq!(&args[..2], ["qe", "System"]);
        assert_eq!(
            args[2],
            "/q:*[System[(Level=1 or Level=2) and TimeCreated[timediff(@SystemTime) <= 86400000]]]"
        );
        assert!(args.contains(&"/f:xml".to_string()));
        assert!(args.contains(&"/c:5".to_string()));
        assert!(!args.iter().any(|a| a.contains("AutoGeneratedDate")));
    }

    #[test]
    fn a_refused_query_is_an_error_not_an_empty_log() {
        // What wevtutil answered to WinMedic's old, bare XPath argument on a
        // German system.
        let refused = CmdOutput::with_output(
            87,
            "Es wurden zu viele Argumente angegeben.\r\nFalscher Parameter.\r\n",
            "",
        );
        let err = read_events(Ok(refused)).unwrap_err();
        assert!(err.contains("exit code 87"), "{err}");
        assert!(err.contains("zu viele Argumente"), "{err}");

        assert!(read_events(Err("not found".to_string())).is_err());
        assert_eq!(read_events(Ok(CmdOutput::ok(""))), Ok(Vec::new()));
    }

    #[test]
    fn output_without_events_parses_to_nothing() {
        assert!(parse_events("").is_empty());
        assert!(parse_events("Es wurden zu viele Argumente angegeben.").is_empty());
    }
}
